### ISSUE TITLE
crashes server (current build)

### ISSUE THREAD

**Issue by SwissalpS** [SmallJoker/player_notes#1]
after activating with '/notes' I clicked the '+'-button and the server crashed.

in callback on_playerReceiveFields()
mods/player_notes/init.lua:69: attempt to index field 'auth_table' (a nil value)

output of --version:
Minetest 5.1.0-dev-cff1e9c (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."

**Comment by SmallJoker** [comment]
Oof. I didn't expect that anyone would still use this mod. However, here you go:
bed6da9
